package initcmd

import (
	"fmt"
	"strings"
)

func renderGitIgnore() string {
	return ".agent/*\ndata/*\n"
}

func renderReadme(options Options) string {
	return fmt.Sprintf(
		"# %s\n\nGenerated by `kumacore`.\n\n## Modules\n\n%s\n\n## Start\n\n1. Run `go run cmd/server/main.go`.\n2. Open `http://127.0.0.1:3000`.\n\nRuntime files are written under `data/`.\n",
		options.ProjectName,
		renderReadmeModules(options.Modules),
	)
}

func renderReadmeModules(moduleIDs []string) string {
	selectedModules := normalizeModuleIDs(moduleIDs)
	if len(selectedModules) == 0 {
		return "- none"
	}

	lines := make([]string, 0, len(selectedModules))
	for _, moduleID := range selectedModules {
		lines = append(lines, "- "+moduleID)
	}

	return strings.Join(lines, "\n")
}

func renderJobImports(metadata RepoMetadata) string {
	return joinSectionLines([]string{
		`	jobslogging "kumacore/app/jobs/logging"`,
	})
}

func renderModuleImports(metadata RepoMetadata) string {
	moduleImports := make([]string, 0, len(metadata.Modules))
	for _, moduleSelection := range metadata.Modules {
		switch moduleSelection.ID {
		case "home":
			moduleImports = append(moduleImports, `	"kumacore/app/modules/home"`)
		case "auth":
			moduleImports = append(moduleImports,
				`	authmiddleware "kumacore/app/middleware/auth"`,
				`	authmodule "kumacore/app/modules/auth"`,
				`	authrepository "kumacore/app/repositories/auth"`,
				`	authservice "kumacore/app/services/auth"`,
			)
		case "health":
			moduleImports = append(moduleImports, `	healthmodule "kumacore/app/modules/health"`)
		}
	}

	return joinSectionLines(moduleImports)
}

func renderModuleSetup(metadata RepoMetadata) string {
	setupLines := make([]string, 0, len(metadata.Modules))
	for _, moduleSelection := range metadata.Modules {
		switch moduleSelection.ID {
		case "home":
			setupLines = append(setupLines, `	homeHandler := home.NewHandler(renderer, configuration.App.Name)`)
		case "auth":
			setupLines = append(setupLines,
				`	authRepository := authrepository.NewRepository(appDatabase)`,
				`	authService, err := authservice.NewService(authRepository, configuration.Core.Session.TTL)`,
				`	if err != nil {`,
				`		log.Fatalf("[server:main] create auth service: %v", err)`,
				`	}`,
				`	authHandler := authmodule.NewHandler(renderer, authService, configuration.Core.App.Dev)`,
			)
		case "health":
			setupLines = append(setupLines,
				`	healthHandler := healthmodule.NewHandler(`,
				`		appDatabase,`,
				`		appDialect,`,
				`		migrate.Source{`,
				`			Backend:    appDialect.Name(),`,
				`			FileSystem: fileSystem,`,
				`			Directory:  "app/migrations/sqlite/app",`,
				`		},`,
				`	)`,
			)
		}
	}

	return joinSectionLines(setupLines)
}

func renderModuleMiddleware(metadata RepoMetadata) string {
	middlewareLines := make([]string, 0, len(metadata.Modules))
	for _, moduleSelection := range metadata.Modules {
		if moduleSelection.ID == "auth" {
			middlewareLines = append(middlewareLines, `			authmiddleware.LoadAuth(authService),`)
		}
	}

	return joinSectionLines(middlewareLines)
}

func renderModuleRoutes(metadata RepoMetadata) string {
	routeLines := make([]string, 0, len(metadata.Modules))
	for _, moduleSelection := range metadata.Modules {
		switch moduleSelection.ID {
		case "home":
			routeLines = append(routeLines, `			home.Routes(homeHandler),`)
		case "auth":
			routeLines = append(routeLines, `			authmodule.Routes(authHandler),`)
		case "health":
			routeLines = append(routeLines, `			healthmodule.Routes(healthHandler),`)
		}
	}

	return joinSectionLines(routeLines)
}

func renderJobRegistrations() string {
	return joinSectionLines([]string{
		`			{`,
		`				Name:     "logging:cleanup",`,
		`				Interval: 24 * time.Hour,`,
		`				Run: func(ctx context.Context, _ any) error {`,
		`					return jobslogging.Cleanup(ctx, configuration.Core.Logging.Dir)`,
		`				},`,
		`			},`,
	})
}

func joinSectionLines(lines []string) string {
	if len(lines) == 0 {
		return ""
	}

	return strings.Join(lines, "\n") + "\n"
}
